# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ySOKOUnxlfpJPTvajdKl_4bKmUk74GGy
"""

!pip install streamlit pandas numpy matplotlib seaborn
import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import GradientBoostingRegressor
from scipy.stats import genextreme as gev

# Optional SHAP import
try:
    import shap
    SHAP_AVAILABLE = True
except Exception:
    SHAP_AVAILABLE = False

st.set_page_config(page_title="Integrated Crop Yield Dashboard", layout="wide")
st.title("🌾 FULL INTEGRATED LIVE DASHBOARD (WITHOUT LIGHTGBM)")

uploaded_file = st.file_uploader("Upload your dataset (CSV)", type=["csv"])

if uploaded_file is not None:
    data = pd.read_csv(uploaded_file)
    st.write("### Dataset Preview")
    st.dataframe(data.head())

    target = "Crop_Yield_MT_per_HA"

    if target not in data.columns:
        st.error(f"Target column '{target}' not found in dataset.")
        st.stop()

    # Preprocessing
    for c in data.columns:
        if data[c].dtype == "object":
            data[c] = data[c].fillna(data[c].mode()[0])
        else:
            data[c] = data[c].fillna(data[c].median())

    cat_cols = [c for c in data.select_dtypes(include="object").columns if c != target]
    df_enc = pd.get_dummies(data, columns=cat_cols, drop_first=True)

    X = df_enc.drop(columns=[target])
    y = df_enc[target]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # Sidebar sliders
    st.sidebar.header("🌱 Interactive Input Controls")
    slider_inputs = {}

    for col in X.columns:
        if np.issubdtype(X[col].dtype, np.number):
            slider_inputs[col] = st.sidebar.slider(
                col,
                float(X[col].min()),
                float(X[col].max()),
                float(X[col].median())
            )

    user_input_df = pd.DataFrame([slider_inputs]).reindex(columns=X_train.columns, fill_value=0)

    if st.button("🚀 Train & Predict"):
        st.info("Training models... please wait")

        # Quantile models using GradientBoostingRegressor
        models = {
            0.1: GradientBoostingRegressor(loss="quantile", alpha=0.1, random_state=42),
            0.5: GradientBoostingRegressor(loss="quantile", alpha=0.5, random_state=42),
            0.9: GradientBoostingRegressor(loss="quantile", alpha=0.9, random_state=42),
        }

        for model in models.values():
            model.fit(X_train, y_train)

        y_lo = models[0.1].predict(X_test)
        y_med = models[0.5].predict(X_test)
        y_hi = models[0.9].predict(X_test)

        # Metrics
        rmse = np.sqrt(mean_squared_error(y_test, y_med))
        r2 = r2_score(y_test, y_med)
        coverage = np.mean((y_test >= y_lo) & (y_test <= y_hi)) * 100
        interval_width = np.mean(y_hi - y_lo)

        c1, c2, c3, c4 = st.columns(4)
        c1.metric("RMSE", f"{rmse:.3f}")
        c2.metric("R²", f"{r2:.3f}")
        c3.metric("Coverage %", f"{coverage:.1f}")
        c4.metric("Interval Width", f"{interval_width:.3f}")

        # User prediction
        user_pred_lo = models[0.1].predict(user_input_df)[0]
        user_pred_med = models[0.5].predict(user_input_df)[0]
        user_pred_hi = models[0.9].predict(user_input_df)[0]

        st.metric("Predicted Yield (Median)", f"{user_pred_med:.2f} MT/ha")
        st.write(f"Uncertainty Range: **{user_pred_lo:.2f} — {user_pred_hi:.2f} MT/ha**")

        # Plot 1
        fig1, ax1 = plt.subplots(figsize=(7, 7))
        ax1.scatter(y_test, y_med, alpha=0.6)
        ax1.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
        ax1.set_title("Actual vs Predicted")
        st.pyplot(fig1)

        # Plot 2
        fig2, ax2 = plt.subplots(figsize=(7, 7))
        ax2.scatter(y_test, y_med, alpha=0.6)
        ax2.fill_between(np.sort(y_test), np.sort(y_lo), np.sort(y_hi), alpha=0.3)
        ax2.set_title("Prediction with Uncertainty Interval")
        st.pyplot(fig2)

        # EVT
        residuals = y_test - y_med
        losses = -residuals[residuals < 0]

        if len(losses) > 3:
            shape, loc, scale = gev.fit(losses)
            extreme_loss = gev.ppf(0.99, shape, loc=loc, scale=scale)

            x = np.linspace(0, max(losses.max(), extreme_loss) * 1.1, 300)
            pdf = gev.pdf(x, shape, loc=loc, scale=scale)

            fig3, ax3 = plt.subplots(figsize=(7, 7))
            ax3.plot(x, pdf)
            ax3.axvline(extreme_loss, linestyle="--")
            ax3.set_title("EVT Tail Risk Curve")
            st.pyplot(fig3)

        # Feature importance
        imp_gain = pd.DataFrame({
            "Feature": X_train.columns,
            "Importance": models[0.5].feature_importances_
        }).sort_values("Importance", ascending=False).head(10)

        fig4, ax4 = plt.subplots(figsize=(8, 6))
        sns.barplot(data=imp_gain, y="Feature", x="Importance", ax=ax4)
        st.pyplot(fig4)

        # SHAP optional
        if SHAP_AVAILABLE:
            try:
                explainer = shap.Explainer(models[0.5], X_train)
                shap_values = explainer(user_input_df)

                fig5 = plt.figure()
                shap.plots.waterfall(shap_values[0], show=False)
                st.pyplot(fig5)
            except Exception:
                st.warning("SHAP available but could not generate explanation.")

        st.success("✅ App runs without LightGBM.")